In [8]:
#读取Excel文件中的数据
import pandas as pd

# 读取excel,
df = pd.read_excel('超市营业额2.xlsx')

# 输出前10行数据
print(df[:10])
print("****"*20)

# 读取第一个worksheet中所有列,
# 跳过第1、3、5行，指定下标为1的列中数据为DataFrame的行索引标签,
df = pd.read_excel('超市营业额2.xlsx',
                   skiprows=[1, 3, 5], index_col=1)
print(df[:10])

     工号  姓名          日期           时段     交易额    柜台
0  1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
1  1002  李四  2019-03-01  14：00-21：00   954.0   化妆品
2  1003  王五  2019-03-01   9：00-14：00  1407.0    食品
3  1004  赵六  2019-03-01  14：00-21：00  1320.0    食品
4  1005  周七  2019-03-01   9：00-14：00   994.0   日用品
5  1006  钱八  2019-03-01  14：00-21：00  1421.0   日用品
6  1006  钱八  2019-03-01   9：00-14：00  1226.0  蔬菜水果
7  1001  张三  2019-03-01  14：00-21：00  1442.0  蔬菜水果
8  1001  张三  2019-03-02   9：00-14：00  1530.0   化妆品
9  1002  李四  2019-03-02  14：00-21：00  1395.0   化妆品
********************************************************************************
      工号          日期           时段     交易额    柜台
姓名
李四  1002  2019-03-01  14：00-21：00   954.0   化妆品
赵六  1004  2019-03-01  14：00-21：00  1320.0    食品
钱八  1006  2019-03-01  14：00-21：00  1421.0   日用品
钱八  1006  2019-03-01   9：00-14：00  1226.0  蔬菜水果
张三  1001  2019-03-01  14：00-21：00  1442.0  蔬菜水果
张三  1001  2019-03-02   9：00-14：00  1530.0   化妆品
李四  1002  2019-03-02  14：00-21：00  1395.0   化妆品
王五  1003  2019-03-02   9：00-14：00   936.0    食品
赵六  1004  2019-03-02  14：00-21：00   906.0    食品
周七  1005  2019-03-02   9：00-14：00  1444.0   日用品

In [12]:
df = pd.read_excel('超市营业额2.xlsx')

print('下标在[5,10]区间的的行'.ljust(20, '='))
# 对行进行切片，注意切片是限定的左闭右开区间
print(df[5:11])

下标在[5,10]区间的的行======
      工号  姓名          日期           时段     交易额    柜台
5   1006  钱八  2019-03-01  14：00-21：00  1421.0   日用品
6   1006  钱八  2019-03-01   9：00-14：00  1226.0  蔬菜水果
7   1001  张三  2019-03-01  14：00-21：00  1442.0  蔬菜水果
8   1001  张三  2019-03-02   9：00-14：00  1530.0   化妆品
9   1002  李四  2019-03-02  14：00-21：00  1395.0   化妆品
10  1003  王五  2019-03-02   9：00-14：00   936.0    食品

In [13]:
# iloc使用数字做索引
print('索引为5的行'.ljust(20, '='))
print(df.iloc[5])

索引为5的行==============
工号            1006
姓名              钱八
日期      2019-03-01
时段     14：00-21：00
交易额           1421
柜台             日用品
Name: 5, dtype: object

In [14]:
print('下标为[3,5,10]的行'.ljust(20, '='))
print(df.iloc[[3, 5, 10], :])

下标为[3,5,10]的行=======
      工号  姓名          日期           时段     交易额   柜台
3   1004  赵六  2019-03-01  14：00-21：00  1320.0   食品
5   1006  钱八  2019-03-01  14：00-21：00  1421.0  日用品
10  1003  王五  2019-03-02   9：00-14：00   936.0   食品

In [15]:
print('行下标为[3,5,10]，列下标为[0,1,4]'.ljust(30, '='))
print(df.iloc[[3, 5, 10], [0, 1, 4]])

行下标为[3,5,10]，列下标为[0,1,4]======
      工号  姓名     交易额
3   1004  赵六  1320.0
5   1006  钱八  1421.0
10  1003  王五   936.0

In [16]:
print('查看指定的列前5行数据'.ljust(20, '='))
print(df[['姓名', '时段', '交易额']][:5])

查看指定的列前5行数据=========
   姓名           时段     交易额
0  张三   9：00-14：00  1664.0
1  李四  14：00-21：00   954.0
2  王五   9：00-14：00  1407.0
3  赵六  14：00-21：00  1320.0
4  周七   9：00-14：00   994.0

In [17]:
print('只查看前10行指定的列'.ljust(20, '='))
print(df[:10][['姓名', '日期', '柜台']])

只查看前10行指定的列=========
   姓名          日期    柜台
0  张三  2019-03-01   化妆品
1  李四  2019-03-01   化妆品
2  王五  2019-03-01    食品
3  赵六  2019-03-01    食品
4  周七  2019-03-01   日用品
5  钱八  2019-03-01   日用品
6  钱八  2019-03-01  蔬菜水果
7  张三  2019-03-01  蔬菜水果
8  张三  2019-03-02   化妆品
9  李四  2019-03-02   化妆品

In [18]:
print('下标为[3,5,10]的行的指定列'.ljust(20, '='))
# loc和at使用标签文本做索引
print(df.loc[[3, 5, 10], ['姓名', '交易额']])

下标为[3,5,10]的行的指定列===
    姓名     交易额
3   赵六  1320.0
5   钱八  1421.0
10  王五   936.0

In [19]:
print('行下标为3,姓名列的值'.ljust(20, '='))
print(df.at[3, '姓名'])

行下标为3,姓名列的值=========
赵六

In [20]:
print('交易额高于1700元的数据'.ljust(20, '='))
print(df[df['交易额'] > 1700])

交易额高于1700元的数据=======
       工号  姓名          日期           时段      交易额    柜台
18   1003  王五  2019-03-03   9：00-14：00   1713.0    食品
47   1005  周七  2019-03-06  14：00-21：00   1778.0  蔬菜水果
48   1003  王五  2019-03-07   9：00-14：00   1713.0   化妆品
82   1006  钱八  2019-03-11   9：00-14：00   1737.0    食品
105  1001  张三  2019-03-14   9：00-14：00  12100.0   日用品
113  1002  李四  2019-03-15   9：00-14：00   1798.0   日用品
121  1002  李四  2019-03-16   9：00-14：00   1788.0   日用品
136  1001  张三  2019-03-17  14：00-21：00   1791.0    食品
185  1004  赵六  2019-03-24   9：00-14：00   1775.0   化妆品
188  1002  李四  2019-03-24  14：00-21：00   1793.0  蔬菜水果
205  1001  张三  2019-03-26   9：00-14：00   1746.0   日用品
223  1003  王五  2019-03-28   9：00-14：00   9031.0    食品
227  1005  周七  2019-03-29   9：00-14：00   1737.0  蔬菜水果
246  1004  赵六  2019-03-31  14：00-21：00   1722.0   日用品

In [22]:
print('交易总额'.ljust(20, '='))
print(df['交易额'].sum())

交易总额================
327257.0

In [23]:
print('下午班的交易总额'.ljust(20, '='))
print(df[df['时段'] == '14：00-21：00']['交易额'].sum())

下午班的交易总额============
151228.0

In [24]:
print('张三下午班的交易情况'.ljust(20, '='))
print(df[(df.姓名 == '张三') & (df.时段 == '14：00-21：00')][:10])

张三下午班的交易情况==========
       工号  姓名          日期           时段     交易额    柜台
7    1001  张三  2019-03-01  14：00-21：00  1442.0  蔬菜水果
39   1001  张三  2019-03-05  14：00-21：00   856.0  蔬菜水果
73   1001  张三  2019-03-10  14：00-21：00  1040.0   化妆品
91   1001  张三  2019-03-12  14：00-21：00  1435.0    食品
99   1001  张三  2019-03-13  14：00-21：00  1333.0    食品
112  1001  张三  2019-03-14  14：00-21：00  1261.0  蔬菜水果
120  1001  张三  2019-03-15  14：00-21：00  1035.0  蔬菜水果
128  1001  张三  2019-03-16  14：00-21：00  1408.0  蔬菜水果
136  1001  张三  2019-03-17  14：00-21：00  1791.0    食品
144  1001  张三  2019-03-18  14：00-21：00  1378.0    食品

In [34]:
print('日用品柜台销售总额'.ljust(20, '='))
print(df[df['柜台'] == '日用品']['交易额'].sum())

日用品柜台销售总额===========
88162.0

In [35]:
print('交易额在指定范围内的记录'.ljust(20, '='))
print(df[df['交易额'].between(800, 850)])

交易额在指定范围内的记录========
       工号  姓名          日期           时段    交易额    柜台
41   1002  李四  2019-03-06  14：00-21：00  822.0   化妆品
55   1002  李四  2019-03-07  14：00-21：00  831.0  蔬菜水果
59   1004  赵六  2019-03-08  14：00-21：00  825.0    食品
86   1003  王五  2019-03-11   9：00-14：00  801.0  蔬菜水果
94   1003  王五  2019-03-12   9：00-14：00  831.0  蔬菜水果
106  1002  李四  2019-03-14  14：00-21：00  822.0   日用品
129  1002  李四  2019-03-17   9：00-14：00  828.0   日用品
132  1006  钱八  2019-03-17  14：00-21：00  840.0  蔬菜水果
137  1002  李四  2019-03-18   9：00-14：00  824.0   化妆品
147  1003  王五  2019-03-19   9：00-14：00  846.0  蔬菜水果
152  1001  张三  2019-03-19  14：00-21：00  844.0    食品
160  1001  张三  2019-03-20  14：00-21：00  829.0    食品
163  1006  钱八  2019-03-21   9：00-14：00  807.0  蔬菜水果
233  1001  张三  2019-03-30  14：00-21：00  850.0   化妆品
248  1006  钱八  2019-03-31  14：00-21：00  812.0    食品

In [36]:
# 读取全部数据，使用默认索引,
df = pd.read_excel('超市营业额2.xlsx')


print('按交易额和工号降序排序'.ljust(20, '='))
print(df.sort_values(by=['交易额', '工号'], ascending=False)[:12])

按交易额和工号降序排序=========
       工号  姓名          日期           时段      交易额    柜台
105  1001  张三  2019-03-14   9：00-14：00  12100.0   日用品
223  1003  王五  2019-03-28   9：00-14：00   9031.0    食品
113  1002  李四  2019-03-15   9：00-14：00   1798.0   日用品
188  1002  李四  2019-03-24  14：00-21：00   1793.0  蔬菜水果
136  1001  张三  2019-03-17  14：00-21：00   1791.0    食品
121  1002  李四  2019-03-16   9：00-14：00   1788.0   日用品
47   1005  周七  2019-03-06  14：00-21：00   1778.0  蔬菜水果
185  1004  赵六  2019-03-24   9：00-14：00   1775.0   化妆品
205  1001  张三  2019-03-26   9：00-14：00   1746.0   日用品
82   1006  钱八  2019-03-11   9：00-14：00   1737.0    食品
227  1005  周七  2019-03-29   9：00-14：00   1737.0  蔬菜水果
246  1004  赵六  2019-03-31  14：00-21：00   1722.0   日用品

In [37]:
print('按交易额降序、工号升序排序'.ljust(20, '='))
print(df.sort_values(by=['交易额', '工号'], ascending=[False, True])[:12])

按交易额降序、工号升序排序=======
       工号  姓名          日期           时段      交易额    柜台
105  1001  张三  2019-03-14   9：00-14：00  12100.0   日用品
223  1003  王五  2019-03-28   9：00-14：00   9031.0    食品
113  1002  李四  2019-03-15   9：00-14：00   1798.0   日用品
188  1002  李四  2019-03-24  14：00-21：00   1793.0  蔬菜水果
136  1001  张三  2019-03-17  14：00-21：00   1791.0    食品
121  1002  李四  2019-03-16   9：00-14：00   1788.0   日用品
47   1005  周七  2019-03-06  14：00-21：00   1778.0  蔬菜水果
185  1004  赵六  2019-03-24   9：00-14：00   1775.0   化妆品
205  1001  张三  2019-03-26   9：00-14：00   1746.0   日用品
227  1005  周七  2019-03-29   9：00-14：00   1737.0  蔬菜水果
82   1006  钱八  2019-03-11   9：00-14：00   1737.0    食品
246  1004  赵六  2019-03-31  14：00-21：00   1722.0   日用品

In [32]:
print('按工号升序排序'.ljust(20, '='))
print(df.sort_values(by='工号', na_position='last')[:10])

按工号升序排序=============
       工号  姓名          日期           时段     交易额    柜台
0    1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
178  1001  张三  2019-03-23  14：00-21：00  1271.0   化妆品
39   1001  张三  2019-03-05  14：00-21：00   856.0  蔬菜水果
40   1001  张三  2019-03-06   9：00-14：00  1037.0   化妆品
177  1001  张三  2019-03-23   9：00-14：00  1296.0   化妆品
169  1001  张三  2019-03-22   9：00-14：00   946.0   化妆品
160  1001  张三  2019-03-20  14：00-21：00   829.0    食品
54   1001  张三  2019-03-07   9：00-14：00  1263.0  蔬菜水果
157  1001  张三  2019-03-20   9：00-14：00  1037.0   日用品
225  1001  张三  2019-03-29  14：00-21：00  1523.0   化妆品

In [33]:
print('按列名升序排序'.ljust(20, '='))
# 注意，这里是按汉字的Unicode编码排序
print(df.sort_index(axis=1, ascending=True)[:10])

按列名升序排序=============
      交易额  姓名    工号          日期           时段    柜台
0  1664.0  张三  1001  2019-03-01   9：00-14：00   化妆品
1   954.0  李四  1002  2019-03-01  14：00-21：00   化妆品
2  1407.0  王五  1003  2019-03-01   9：00-14：00    食品
3  1320.0  赵六  1004  2019-03-01  14：00-21：00    食品
4   994.0  周七  1005  2019-03-01   9：00-14：00   日用品
5  1421.0  钱八  1006  2019-03-01  14：00-21：00   日用品
6  1226.0  钱八  1006  2019-03-01   9：00-14：00  蔬菜水果
7  1442.0  张三  1001  2019-03-01  14：00-21：00  蔬菜水果
8  1530.0  张三  1001  2019-03-02   9：00-14：00   化妆品
9  1395.0  李四  1002  2019-03-02  14：00-21：00   化妆品